In [2]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\jagadeesh\anaconda3\lib\site-packages (24.0.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os

print(os.path.getsize("invoice_data.parquet"))

17975158

In [4]:
with open("invoice_data.parquet", "rb") as f:
    print(f.read(4))

b'PAR1'

In [5]:
pip install fastparquet

Requirement already satisfied: fastparquet in c:\users\jagadeesh\anaconda3\lib\site-packages (2026.5.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\jagadeesh\anaconda3\lib\site-packages (from fastparquet) (2.2.3)
Requirement already satisfied: numpy in c:\users\jagadeesh\anaconda3\lib\site-packages (from fastparquet) (2.1.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\jagadeesh\anaconda3\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\jagadeesh\anaconda3\lib\site-packages (from fastparquet) (2025.3.2)
Requirement already satisfied: packaging in c:\users\jagadeesh\anaconda3\lib\site-packages (from fastparquet) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jagadeesh\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jagadeesh\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jagadeesh\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jagadeesh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pyarrow
import pandas

print("PyArrow:", pyarrow.__version__)
print("Pandas:", pandas.__version__)

PyArrow: 24.0.0
Pandas: 2.2.3

In [7]:
pip install --upgrade pyarrow

Requirement already satisfied: pyarrow in c:\users\jagadeesh\anaconda3\lib\site-packages (24.0.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

df = pd.read_parquet("invoice_data.parquet", engine="pyarrow")
df.head()

,billNumber,orderItems,orderUserInfo,paymentLinks,lastUpdatedTime,splitInvoices,versionNumber,paymentInfo,deliveryPersons,fseName,...,billingInfo,invoiceRefundStatus,tokenNos,updatedFrom,endTime,checkUnSettledOrders,startTime,response,closeOrders,documentType
0,373,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...","{'amount': 160.0, 'createdTime': '2026-05-15T0...",1778772302508,False,3.0,"{'gateway': 'easebuzz', 'mode': 'none', 'multi...",[],Ideal Kitchen (Beeramguda),...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[332],webhook,None,<NA>,None,<NA>,<NA>,None
1,374,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...","{'amount': 160.0, 'createdTime': '2026-05-15T0...",1778772405781,False,3.0,"{'gateway': 'none', 'mode': 'none', 'multipleP...",[],Ideal Kitchen (Beeramguda),...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[333],None,None,<NA>,None,<NA>,<NA>,None
2,1119,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783404604,False,3.0,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",[],Panthashala Food Court,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None
3,21172,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783421058,False,3.0,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",[],City Pearl Restaurant,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None
4,1111,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783446908,False,3.0,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",None,Chocoloco,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53336 entries, 0 to 53335
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   billNumber                53336 non-null  int64
 1   orderItems                53336 non-null  object
 2   orderUserInfo             53336 non-null  object
 3   paymentLinks              8268 non-null   object
 4   lastUpdatedTime           53336 non-null  int64
 5   splitInvoices             53324 non-null  boolean
 6   versionNumber             53324 non-null  float64
 7   paymentInfo               53336 non-null  object
 8   deliveryPersons           19257 non-null  object
 9   fseName                   53336 non-null  object
 10  status                    53336 non-null  object
 11  splittedTableNos          53336 non-null  object
 12  fseId                     53336 non-null  object
 13  activeStatus              53336 non-null  object
 14  targetInfos               53336 non-null  object
 15  version                   53336 non-null  object
 16  splitBillSummaryList      53324 non-null  object
 17  notes                     0 non-null      float64
 18  includeAmountInQr         19256 non-null  boolean
 19  kotNos                    53336 non-null  object
 20  invoicePaymentType        53336 non-null  object
 21  orderIds                  53336 non-null  object
 22  invoiceConfigurationInfo  53336 non-null  object
 23  createdTime               53336 non-null  int64
 24  orderTypes                53336 non-null  object
 25  billingModes              53336 non-null  object
 26  paymentNotes              53336 non-null  object
 27  id                        53336 non-null  object
 28  invoiceId                 53336 non-null  object
 29  orderNumbers              53336 non-null  object
 30  handledBy                 53326 non-null  object
 31  invoicePaymentStatus      53336 non-null  object
 32  paymentVouchers           53336 non-null  object
 33  generatedOrderIds         53336 non-null  object
 34  tableNumbers              53336 non-null  object
 35  offerInfo                 164 non-null    object
 36  targetNumbers             53336 non-null  object
 37  orderSources              53336 non-null  object
 38  orderIdentifiers          53336 non-null  object
 39  splitBillBehaviour        45440 non-null  boolean
 40  billingInfo               53336 non-null  object
 41  invoiceRefundStatus       53336 non-null  object
 42  tokenNos                  53336 non-null  object
 43  updatedFrom               15763 non-null  object
 44  endTime                   7878 non-null   object
 45  checkUnSettledOrders      7878 non-null   boolean
 46  startTime                 7878 non-null   object
 47  response                  2 non-null      boolean
 48  closeOrders               0 non-null      boolean
 49  documentType              2 non-null      object
dtypes: boolean(6), float64(2), int64(3), object(39)
memory usage: 18.5+ MB

In [10]:
print(df.isnull().sum())

billNumber                      0
orderItems                      0
orderUserInfo                   0
paymentLinks                45068
lastUpdatedTime                 0
splitInvoices                  12
versionNumber                  12
paymentInfo                     0
deliveryPersons             34079
fseName                         0
status                          0
splittedTableNos                0
fseId                           0
activeStatus                    0
targetInfos                     0
version                         0
splitBillSummaryList           12
notes                       53336
includeAmountInQr           34080
kotNos                          0
invoicePaymentType              0
orderIds                        0
invoiceConfigurationInfo        0
createdTime                     0
orderTypes                      0
billingModes                    0
paymentNotes                    0
id                              0
invoiceId                       0
orderNumbers                    0
handledBy                      10
invoicePaymentStatus            0
paymentVouchers                 0
generatedOrderIds               0
tableNumbers                    0
offerInfo                   53172
targetNumbers                   0
orderSources                    0
orderIdentifiers                0
splitBillBehaviour           7896
billingInfo                     0
invoiceRefundStatus             0
tokenNos                        0
updatedFrom                 37573
endTime                     45458
checkUnSettledOrders        45458
startTime                   45458
response                    53334
closeOrders                 53336
documentType                53334
dtype: int64

In [11]:
print(df.shape)
df.head()

(53336, 50)

,billNumber,orderItems,orderUserInfo,paymentLinks,lastUpdatedTime,splitInvoices,versionNumber,paymentInfo,deliveryPersons,fseName,...,billingInfo,invoiceRefundStatus,tokenNos,updatedFrom,endTime,checkUnSettledOrders,startTime,response,closeOrders,documentType
0,373,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...","{'amount': 160.0, 'createdTime': '2026-05-15T0...",1778772302508,False,3.0,"{'gateway': 'easebuzz', 'mode': 'none', 'multi...",[],Ideal Kitchen (Beeramguda),...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[332],webhook,None,<NA>,None,<NA>,<NA>,None
1,374,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...","{'amount': 160.0, 'createdTime': '2026-05-15T0...",1778772405781,False,3.0,"{'gateway': 'none', 'mode': 'none', 'multipleP...",[],Ideal Kitchen (Beeramguda),...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[333],None,None,<NA>,None,<NA>,<NA>,None
2,1119,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783404604,False,3.0,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",[],Panthashala Food Court,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None
3,21172,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783421058,False,3.0,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",[],City Pearl Restaurant,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None
4,1111,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",None,1778783446908,False,3.0,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",None,Chocoloco,...,"{'actualCost': None, 'actualDeliveryCharge': 0...",none,[1],None,None,<NA>,None,<NA>,<NA>,None

In [12]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53336 entries, 0 to 53335
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   billNumber                53336 non-null  int64
 1   orderItems                53336 non-null  object
 2   orderUserInfo             53336 non-null  object
 3   paymentLinks              8268 non-null   object
 4   lastUpdatedTime           53336 non-null  int64
 5   splitInvoices             53324 non-null  boolean
 6   versionNumber             53324 non-null  float64
 7   paymentInfo               53336 non-null  object
 8   deliveryPersons           19257 non-null  object
 9   fseName                   53336 non-null  object
 10  status                    53336 non-null  object
 11  splittedTableNos          53336 non-null  object
 12  fseId                     53336 non-null  object
 13  activeStatus              53336 non-null  object
 14  targetInfos               53336 non-null  object
 15  version                   53336 non-null  object
 16  splitBillSummaryList      53324 non-null  object
 17  notes                     0 non-null      float64
 18  includeAmountInQr         19256 non-null  boolean
 19  kotNos                    53336 non-null  object
 20  invoicePaymentType        53336 non-null  object
 21  orderIds                  53336 non-null  object
 22  invoiceConfigurationInfo  53336 non-null  object
 23  createdTime               53336 non-null  int64
 24  orderTypes                53336 non-null  object
 25  billingModes              53336 non-null  object
 26  paymentNotes              53336 non-null  object
 27  id                        53336 non-null  object
 28  invoiceId                 53336 non-null  object
 29  orderNumbers              53336 non-null  object
 30  handledBy                 53326 non-null  object
 31  invoicePaymentStatus      53336 non-null  object
 32  paymentVouchers           53336 non-null  object
 33  generatedOrderIds         53336 non-null  object
 34  tableNumbers              53336 non-null  object
 35  offerInfo                 164 non-null    object
 36  targetNumbers             53336 non-null  object
 37  orderSources              53336 non-null  object
 38  orderIdentifiers          53336 non-null  object
 39  splitBillBehaviour        45440 non-null  boolean
 40  billingInfo               53336 non-null  object
 41  invoiceRefundStatus       53336 non-null  object
 42  tokenNos                  53336 non-null  object
 43  updatedFrom               15763 non-null  object
 44  endTime                   7878 non-null   object
 45  checkUnSettledOrders      7878 non-null   boolean
 46  startTime                 7878 non-null   object
 47  response                  2 non-null      boolean
 48  closeOrders               0 non-null      boolean
 49  documentType              2 non-null      object
dtypes: boolean(6), float64(2), int64(3), object(39)
memory usage: 18.5+ MB

In [13]:
print(df['paymentInfo'].iloc[0])

{'gateway': 'easebuzz', 'mode': 'none', 'multiplePaymentInfo': None, 'status': 'failed', 'summary': None}

In [14]:
df['payment_mode'] = df['paymentInfo'].apply(
    lambda x: x.get('mode') if isinstance(x, dict) else None
)

In [15]:
print(df['payment_mode'].value_counts())

payment_mode
upi         24399
cash        20500
gateway      6239
cards         846
none          799
other         281
multiple      125
noCharge       87
credit         33
swiggy         22
zomato          5
Name: count, dtype: int64

In [16]:
cols_to_drop = [
    'notes',
    'closeOrders',
    'response',
    'documentType',
    'offerInfo',
    'paymentLinks',
    'endTime',
    'startTime',
    'checkUnSettledOrders',
    'updatedFrom',
    'includeAmountInQr'
]

df = df.drop(columns=cols_to_drop)

In [17]:
print(df.shape)

(53336, 40)

In [18]:
df.isnull().sum()

billNumber                      0
orderItems                      0
orderUserInfo                   0
lastUpdatedTime                 0
splitInvoices                  12
versionNumber                  12
paymentInfo                     0
deliveryPersons             34079
fseName                         0
status                          0
splittedTableNos                0
fseId                           0
activeStatus                    0
targetInfos                     0
version                         0
splitBillSummaryList           12
kotNos                          0
invoicePaymentType              0
orderIds                        0
invoiceConfigurationInfo        0
createdTime                     0
orderTypes                      0
billingModes                    0
paymentNotes                    0
id                              0
invoiceId                       0
orderNumbers                    0
handledBy                      10
invoicePaymentStatus            0
paymentVouchers                 0
generatedOrderIds               0
tableNumbers                    0
targetNumbers                   0
orderSources                    0
orderIdentifiers                0
splitBillBehaviour           7896
billingInfo                     0
invoiceRefundStatus             0
tokenNos                        0
payment_mode                    0
dtype: int64

In [19]:
cols_to_drop = [
    'deliveryPersons',      # 34079 missing
    'splitBillBehaviour',   # 7896 missing
    'splitInvoices',
    'versionNumber',
    'splitBillSummaryList',
    'targetInfos',
    'version',
    'invoiceConfigurationInfo',
    'generatedOrderIds',
    'orderIdentifiers',
    'splittedTableNos',
    'fseId',
    'activeStatus',
    'paymentVouchers',
    'paymentNotes',
    'tokenNos',
    'targetNumbers'
]

df = df.drop(columns=cols_to_drop)

print(df.shape)
print(df.columns)

(53336, 23)
Index(['billNumber', 'orderItems', 'orderUserInfo', 'lastUpdatedTime',
       'paymentInfo', 'fseName', 'status', 'kotNos', 'invoicePaymentType',
       'orderIds', 'createdTime', 'orderTypes', 'billingModes', 'id',
       'invoiceId', 'orderNumbers', 'handledBy', 'invoicePaymentStatus',
       'tableNumbers', 'orderSources', 'billingInfo', 'invoiceRefundStatus',
       'payment_mode'],
      dtype='object')

In [20]:
df.isnull().sum()

billNumber               0
orderItems               0
orderUserInfo            0
lastUpdatedTime          0
paymentInfo              0
fseName                  0
status                   0
kotNos                   0
invoicePaymentType       0
orderIds                 0
createdTime              0
orderTypes               0
billingModes             0
id                       0
invoiceId                0
orderNumbers             0
handledBy               10
invoicePaymentStatus     0
tableNumbers             0
orderSources             0
billingInfo              0
invoiceRefundStatus      0
payment_mode             0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53336 entries, 0 to 53335
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   billNumber            53336 non-null  int64
 1   orderItems            53336 non-null  object
 2   orderUserInfo         53336 non-null  object
 3   lastUpdatedTime       53336 non-null  int64
 4   paymentInfo           53336 non-null  object
 5   fseName               53336 non-null  object
 6   status                53336 non-null  object
 7   kotNos                53336 non-null  object
 8   invoicePaymentType    53336 non-null  object
 9   orderIds              53336 non-null  object
 10  createdTime           53336 non-null  int64
 11  orderTypes            53336 non-null  object
 12  billingModes          53336 non-null  object
 13  id                    53336 non-null  object
 14  invoiceId             53336 non-null  object
 15  orderNumbers          53336 non-null  object
 16  handledBy             53326 non-null  object
 17  invoicePaymentStatus  53336 non-null  object
 18  tableNumbers          53336 non-null  object
 19  orderSources          53336 non-null  object
 20  billingInfo           53336 non-null  object
 21  invoiceRefundStatus   53336 non-null  object
 22  payment_mode          53336 non-null  object
dtypes: int64(3), object(20)
memory usage: 9.4+ MB

In [22]:
df['createdTime'] = pd.to_datetime(df['createdTime'], unit='ms')
df['createdTime'] = df['createdTime'].dt.strftime('%Y-%m-%d %H:%M')

In [23]:
df['lastUpdatedTime'] = pd.to_datetime(df['lastUpdatedTime'], unit='ms')
df['lastUpdatedTime'] = df['lastUpdatedTime'].dt.strftime('%Y-%m-%d %H:%M')

In [24]:

df[['createdTime', 'lastUpdatedTime']].head()

        createdTime   lastUpdatedTime
0  2026-05-15 01:29  2026-05-14 15:25
1  2026-05-15 01:30  2026-05-14 15:26
2  2026-05-14 18:30  2026-05-14 18:30
3  2026-05-14 18:30  2026-05-14 18:30
4  2026-05-14 18:30  2026-05-14 18:30

In [25]:
df['createdTime'] = pd.to_datetime(df['createdTime'])
df['lastUpdatedTime'] = pd.to_datetime(df['lastUpdatedTime'])

In [26]:
def time_slot(hour):
    if 0 <= hour < 6:
        return 'Late Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 22:
        return 'Evening'
    else:
        return 'Night'

df['hour'] = pd.to_datetime(df['createdTime']).dt.hour
df['time_slot'] = df['hour'].apply(time_slot)

In [27]:
df['hour'] = pd.to_datetime(df['createdTime']).dt.hour
df['date'] = pd.to_datetime(df['createdTime']).dt.date
df['day_name'] = pd.to_datetime(df['createdTime']).dt.day_name()
df['month'] = pd.to_datetime(df['createdTime']).dt.month_name()
df[['createdTime','date','hour','day_name','month','time_slot']].head()

          createdTime        date  hour  day_name month   time_slot
0 2026-05-15 01:29:00  2026-05-15     1    Friday   May  Late Night
1 2026-05-15 01:30:00  2026-05-15     1    Friday   May  Late Night
2 2026-05-14 18:30:00  2026-05-14    18  Thursday   May     Evening
3 2026-05-14 18:30:00  2026-05-14    18  Thursday   May     Evening
4 2026-05-14 18:30:00  2026-05-14    18  Thursday   May     Evening

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53336 entries, 0 to 53335
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   billNumber            53336 non-null  int64
 1   orderItems            53336 non-null  object
 2   orderUserInfo         53336 non-null  object
 3   lastUpdatedTime       53336 non-null  datetime64[ns]
 4   paymentInfo           53336 non-null  object
 5   fseName               53336 non-null  object
 6   status                53336 non-null  object
 7   kotNos                53336 non-null  object
 8   invoicePaymentType    53336 non-null  object
 9   orderIds              53336 non-null  object
 10  createdTime           53336 non-null  datetime64[ns]
 11  orderTypes            53336 non-null  object
 12  billingModes          53336 non-null  object
 13  id                    53336 non-null  object
 14  invoiceId             53336 non-null  object
 15  orderNumbers          53336 non-null  object
 16  handledBy             53326 non-null  object
 17  invoicePaymentStatus  53336 non-null  object
 18  tableNumbers          53336 non-null  object
 19  orderSources          53336 non-null  object
 20  billingInfo           53336 non-null  object
 21  invoiceRefundStatus   53336 non-null  object
 22  payment_mode          53336 non-null  object
 23  hour                  53336 non-null  int32
 24  time_slot             53336 non-null  object
 25  date                  53336 non-null  object
 26  day_name              53336 non-null  object
 27  month                 53336 non-null  object
dtypes: datetime64[ns](2), int32(1), int64(1), object(24)
memory usage: 11.2+ MB

In [29]:
print(df['billingInfo'].iloc[0])

{'actualCost': None, 'actualDeliveryCharge': 0.0, 'actualPackingCharge': 0.0, 'beforeOfferCost': 160.0, 'billingInfoStage': 'generated', 'charges': array([], dtype=object), 'complementaryItemDiscount': 0.0, 'computedFinalCost': None, 'currency': 'INR', 'deliveryCharge': 0.0, 'discount': 0.0, 'finalCost': None, 'handlingCharge': 0.0, 'handlingChargePercentage': 0.0, 'itemCount': None, 'offerAmount': 0.0, 'offerPercentage': 0.0, 'packingCharge': 0.0, 'roundingAmount': 0.0, 'serviceCharge': 0.0, 'serviceChargePercentage': 0.0, 'subTotal': 160.0, 'tax': 0.0, 'taxDiscount': None, 'tip': 0.0, 'totalCost': 160.0}

In [30]:
df['fseName'].nunique()

209

In [31]:
df['orderTypes'].value_counts()

orderTypes
[dineIn]      27640
[takeAway]    22045
[pickUp]       2134
[roomDine]     1488
[delivery]       29
Name: count, dtype: int64

In [32]:
df['payment_mode'].value_counts()

payment_mode
upi         24399
cash        20500
gateway      6239
cards         846
none          799
other         281
multiple      125
noCharge       87
credit         33
swiggy         22
zomato          5
Name: count, dtype: int64

In [33]:
df['status'].value_counts()

status
closed       52475
open           650
cancelled      211
Name: count, dtype: int64

In [34]:
df['invoicePaymentStatus'].value_counts()

invoicePaymentStatus
paid             52489
notPaid            812
credit              33
partiallyPaid        2
Name: count, dtype: int64

In [35]:
df['fseName'].value_counts().head(10)

fseName
Coffi Bar                                        2735
Hotel Shankar Villas                             2452
Ideal Kitchen                                    2019
Amogha Cafe & Hotel                              1784
Hotel Mannat Grand                               1572
Ideal Kitchen (Beeramguda)                       1446
Neelavali's Kitchen                              1294
Sri Guru Raghavendra Udupi Veg                   1284
PRATARASAH                                       1193
Royal Sridevi Veg And Non Veg - Gajularamaram    1040
Name: count, dtype: int64

In [36]:
print("BillNumber duplicates:", df['billNumber'].duplicated().sum())
print("InvoiceId duplicates:", df['invoiceId'].duplicated().sum())
print("ID duplicates:", df['id'].duplicated().sum())

BillNumber duplicates: 26655
InvoiceId duplicates: 22570
ID duplicates: 0

In [37]:
duplicates = df[df['billNumber'].duplicated(keep=False)]

print(duplicates[['billNumber']])

       billNumber
0             373
1             374
2            1119
3           21172
4            1111
...           ...
53331        4655
53332        4695
53333        4712
53334        4681
53335        4704

[40531 rows x 1 columns]

In [38]:
df[df['billNumber'] == 1001][
    ['billNumber', 'status', 'createdTime', 'lastUpdatedTime']
]

       billNumber  status         createdTime     lastUpdatedTime
901          1001  closed 2026-05-15 01:53:00 2026-05-15 01:53:00
19002        1001  closed 2026-05-15 15:02:00 2026-05-15 15:02:00
21245        1001  closed 2026-05-15 15:52:00 2026-05-15 15:53:00
50568        1001  closed 2026-05-16 16:46:00 2026-05-16 16:52:00

In [39]:
df = df.sort_values('lastUpdatedTime')

df_latest = df.drop_duplicates(
    subset='billNumber',
    keep='last'
)

In [40]:
print(
    (df.groupby('billNumber')['status'].nunique() > 1).sum()
)

679

In [41]:
# Make sure lastUpdatedTime is datetime
df['lastUpdatedTime'] = pd.to_datetime(df['lastUpdatedTime'])

# Sort by latest update time
df = df.sort_values('lastUpdatedTime')

# Keep only the latest record for each billNumber
df = df.drop_duplicates(
    subset='billNumber',
    keep='last'
)

In [42]:
print("Duplicate bill numbers:", df['billNumber'].duplicated().sum())

Duplicate bill numbers: 0

In [43]:
df[df['billNumber'] == 1001][
    ['billNumber', 'status', 'createdTime', 'lastUpdatedTime']
]

       billNumber  status         createdTime     lastUpdatedTime
50568        1001  closed 2026-05-16 16:46:00 2026-05-16 16:52:00

In [44]:
rows_before = len(df)

df = df.sort_values('lastUpdatedTime')
df = df.drop_duplicates(subset='billNumber', keep='last')

rows_after = len(df)

print("Rows removed:", rows_before - rows_after)

Rows removed: 0

In [45]:
print("BillNumber duplicates:", df['billNumber'].duplicated().sum())
print("InvoiceId duplicates:", df['invoiceId'].duplicated().sum())
print("ID duplicates:", df['id'].duplicated().sum())

BillNumber duplicates: 0
InvoiceId duplicates: 0
ID duplicates: 0

In [46]:
print(df.shape)

(26681, 28)

In [47]:
print(df['billingInfo'].iloc[0])

{'actualCost': None, 'actualDeliveryCharge': 0.0, 'actualPackingCharge': 0.0, 'beforeOfferCost': 150.0, 'billingInfoStage': 'paid', 'charges': array([], dtype=object), 'complementaryItemDiscount': 0.0, 'computedFinalCost': None, 'currency': 'INR', 'deliveryCharge': 0.0, 'discount': 0.0, 'finalCost': None, 'handlingCharge': 0.0, 'handlingChargePercentage': 0.0, 'itemCount': None, 'offerAmount': 0.0, 'offerPercentage': 0.0, 'packingCharge': 0.0, 'roundingAmount': 0.0, 'serviceCharge': 0.0, 'serviceChargePercentage': 0.0, 'subTotal': 150.0, 'tax': 0.0, 'taxDiscount': None, 'tip': 0.0, 'totalCost': 150.0}

In [48]:
df['revenue'] = df['billingInfo'].apply(
    lambda x: x.get('totalCost') if isinstance(x, dict) else None
)

In [49]:
df[['revenue']].head()

    revenue
11    150.0
16     30.0
19    140.0
33     90.0
59     60.0

In [50]:
print("Total Revenue: ₹", df['revenue'].sum())
print("Average Order Value: ₹", round(df['revenue'].mean(), 2))
df['date'] = pd.to_datetime(df['createdTime']).dt.date

daily_revenue = df.groupby('date')['revenue'].sum()

print(daily_revenue)

Total Revenue: ₹ 5427618.0
Average Order Value: ₹ 203.43
date
2026-05-14       6766.0
2026-05-15    1197245.0
2026-05-16    4223607.0
Name: revenue, dtype: float64

In [51]:
print("Total Revenue: ₹", df['revenue'].sum())

Total Revenue: ₹ 5427618.0

In [52]:
df.groupby('payment_mode')['revenue'].sum().sort_values(ascending=False)

payment_mode
upi         2552834.0
cash        1537981.0
gateway      629032.0
cards        372464.0
none         110963.0
credit        69945.0
other         67950.0
noCharge      30977.0
swiggy        27942.0
multiple      24258.0
zomato         3272.0
Name: revenue, dtype: float64

In [53]:
print(df['payment_mode'].dtype)

object

In [54]:
print(df['payment_mode'].apply(type).value_counts())

payment_mode
<class 'str'>    26681
Name: count, dtype: int64

In [55]:
df['revenue'].apply(type).value_counts()

revenue
<class 'float'>    26681
Name: count, dtype: int64

In [56]:
print(df[['payment_mode', 'revenue']].head())
print(df[['payment_mode', 'revenue']].dtypes)
print(df.groupby('payment_mode').size())

   payment_mode  revenue
11         cash    150.0
16         cash     30.0
19         cash    140.0
33         cash     90.0
59         cash     60.0
payment_mode     object
revenue         float64
dtype: object
payment_mode
cards         284
cash        11697
credit         10
gateway      2962
multiple       35
noCharge       41
none          230
other         172
swiggy         12
upi         11236
zomato          2
dtype: int64

In [57]:
top_restaurants = df.groupby('fseName')['revenue'].sum()

top_restaurants.sort_values(ascending=False).head(1000)

fseName
THE GOLDEN CAVE RESTAURANT         296840.0
The Wine Dine Bar & Restaurant     264766.0
Hotel Shankar Villas               211020.0
Ideal Kitchen                      208610.0
Friends Restaurant                 144545.0
                                     ...
Chittoor Naidu                        250.0
Mana Inti Bhojanam                    229.0
Babai Tea Junction                     20.0
Radha's Kitchen                         7.0
Yashpal Food Court                      1.0
Name: revenue, Length: 184, dtype: float64

In [58]:
df['orderTypes'].apply(type).value_counts()

orderTypes
<class 'numpy.ndarray'>    26681
Name: count, dtype: int64

In [59]:
df['orderTypes'] = df['orderTypes'].apply(
    lambda x: x[0] if len(x) > 0 else None
)

In [60]:
df['orderTypes'].apply(type).value_counts()

orderTypes
<class 'str'>    26681
Name: count, dtype: int64

In [61]:
df.groupby('orderTypes')['revenue'].sum().sort_values(ascending=False)

orderTypes
dineIn      3416450.0
takeAway    1370853.0
pickUp       349304.0
roomDine     275716.0
delivery      15295.0
Name: revenue, dtype: float64

In [62]:
print("Total Revenue: ₹", df['revenue'].sum())
print("Average Order Value: ₹", df['revenue'].mean())

Total Revenue: ₹ 5427618.0
Average Order Value: ₹ 203.4263333458266

In [63]:
df.groupby('day_name')['revenue'].sum()

day_name
Friday      1197245.0
Saturday    4223607.0
Thursday       6766.0
Name: revenue, dtype: float64

In [64]:
df[df['status'] == 'cancelled']['revenue'].sum()

np.float64(81438.0)

In [65]:
df[df['invoicePaymentStatus'] == 'paid']['revenue'].sum()

np.float64(5246710.0)

In [66]:
df['createdTime'] = pd.to_datetime(df['createdTime'])

print("Start Date:", df['createdTime'].min())
print("End Date:", df['createdTime'].max())

Start Date: 2026-05-14 18:31:00
End Date: 2026-05-16 22:12:00

In [67]:
(df['createdTime'].max() - df['createdTime'].min()).days

2

In [68]:
#df.to_excel("cleaned_data.xlsx", index=False)

In [69]:
#import os
print(os.listdir())

['.anaconda', '.antigravity', '.arduinoIDE', '.bash_history', '.cache', '.codex', '.conda', '.condarc', '.config', '.continuum', '.copilot', '.cursor', '.eclipse', '.gemini', '.gitconfig', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.m2', '.mamba', '.matplotlib', '.p2', '.python_history', '.qoder', '.rustup', '.sts4', '.vscode', '.vscode-shared', 'anaconda3', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'country_wise_latest.csv', 'covid_19_clean_complete.csv', 'CrossDevice', 'datascience.ipynb', 'data_cleaned.xlsx', 'day_wise.csv', 'Documents', 'Downloads', 'eclipse', 'eclipse-workspace', 'Favorites', 'flipkart.xlsx', 'flipkart_com-ecommerce_sample.csv', 'flipkart_com-ecommerce_sample.ipynb', 'full_grouped.csv', 'invoice_data.parquet', 'jack.xlsx', 'Links', 'Local Settings', 'Microsoft', 'ml task2.ipynb', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{c4ee31c0-8560-11f0-9684-bc75ba6a2ee2}.TM.blf', 'NTUSER.DAT{c4ee31c0-8560-11f0-9684-bc75ba6a2ee2}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{c4ee31c0-8560-11f0-9684-bc75ba6a2ee2}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Portuguese.csv', 'Postman', 'PrintHood', 'ps.py', 'random.ipynb', 'Recent', 'RESUME.ipynb', 'Saved Games', 'Searches', 'SendTo', 'source', 'spotify.ipynb', 'spotify_2015_2025_85k.csv', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'usa_county_wise.csv', 'Videos', 'worldometer_data.csv']

In [70]:
#print(os.getcwd())

In [71]:
df

,billNumber,orderItems,orderUserInfo,lastUpdatedTime,paymentInfo,fseName,status,kotNos,invoicePaymentType,orderIds,...,orderSources,billingInfo,invoiceRefundStatus,payment_mode,hour,time_slot,date,day_name,month,revenue
11,51965,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-14 18:31:00,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",Hotel Shankar Villas,closed,[1117],full,[c4fvJazBKQ0eQ5CUX8i5],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,cash,18,Evening,2026-05-14,Thursday,May,150.0
16,51966,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-14 18:32:00,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",Hotel Shankar Villas,closed,[1118],full,[hNjtSRIzQ8R3kTbswqEw],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,cash,18,Evening,2026-05-14,Thursday,May,30.0
19,51967,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-14 18:32:00,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",Hotel Shankar Villas,closed,[1119],full,[KLDmzM1uZqcrzt9fri1s],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,cash,18,Evening,2026-05-14,Thursday,May,140.0
33,51968,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-14 18:35:00,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",Hotel Shankar Villas,closed,[1120],full,[YgmYxZeTKzFxo7ak3kSz],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,cash,18,Evening,2026-05-14,Thursday,May,90.0
59,51970,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-14 18:41:00,"{'gateway': 'none', 'mode': 'cash', 'multipleP...",Hotel Shankar Villas,closed,[1122],full,[t9zvcIUV8K8n1bUUM9aD],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,cash,18,Evening,2026-05-14,Thursday,May,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53239,4609,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-17 18:36:00,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",GOKUL PURE VEG RESTAURANT,closed,[49],full,[Cvd7YnueFsEThKCtSmcV],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,upi,12,Afternoon,2026-05-16,Saturday,May,30.0
53238,4619,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-17 18:36:00,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",GOKUL PURE VEG RESTAURANT,closed,[62],full,[iaTQqDvvXcwTZ1ljhflj],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,upi,13,Afternoon,2026-05-16,Saturday,May,114.0
53237,4610,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-17 18:36:00,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",GOKUL PURE VEG RESTAURANT,closed,[50],full,[qw56rFNhihYmVeQXITK8],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,upi,12,Afternoon,2026-05-16,Saturday,May,30.0
53250,4517,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-17 18:36:00,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",GOKUL PURE VEG RESTAURANT,closed,[25],full,[XdIdx9cn3UpQr6yKDD5K],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,upi,11,Morning,2026-05-15,Friday,May,60.0
53335,4704,"[{'additionalDiscount': 0.0, 'additionalDiscou...","{'allergens': [], 'countryCode': '91', 'email'...",2026-05-17 18:36:00,"{'gateway': 'none', 'mode': 'upi', 'multiplePa...",GOKUL PURE VEG RESTAURANT,closed,[180],full,[STsR0Db3YmjWaAUgDEBx],...,[nutrimony],"{'actualCost': None, 'actualDeliveryCharge': 0...",none,upi,16,Afternoon,2026-05-16,Saturday,May,515.0

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26681 entries, 11 to 53335
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   billNumber            26681 non-null  int64
 1   orderItems            26681 non-null  object
 2   orderUserInfo         26681 non-null  object
 3   lastUpdatedTime       26681 non-null  datetime64[ns]
 4   paymentInfo           26681 non-null  object
 5   fseName               26681 non-null  object
 6   status                26681 non-null  object
 7   kotNos                26681 non-null  object
 8   invoicePaymentType    26681 non-null  object
 9   orderIds              26681 non-null  object
 10  createdTime           26681 non-null  datetime64[ns]
 11  orderTypes            26681 non-null  object
 12  billingModes          26681 non-null  object
 13  id                    26681 non-null  object
 14  invoiceId             26681 non-null  object
 15  orderNumbers          26681 non-null  object
 16  handledBy             26679 non-null  object
 17  invoicePaymentStatus  26681 non-null  object
 18  tableNumbers          26681 non-null  object
 19  orderSources          26681 non-null  object
 20  billingInfo           26681 non-null  object
 21  invoiceRefundStatus   26681 non-null  object
 22  payment_mode          26681 non-null  object
 23  hour                  26681 non-null  int32
 24  time_slot             26681 non-null  object
 25  date                  26681 non-null  object
 26  day_name              26681 non-null  object
 27  month                 26681 non-null  object
 28  revenue               26681 non-null  float64
dtypes: datetime64[ns](2), float64(1), int32(1), int64(1), object(24)
memory usage: 6.0+ MB

In [73]:
df['handledBy'].isnull().sum()

np.int64(2)

In [74]:
df['date'] = pd.to_datetime(df['date'])

In [75]:
df['handledBy'] = df['handledBy'].fillna('Unknown')

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26681 entries, 11 to 53335
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   billNumber            26681 non-null  int64
 1   orderItems            26681 non-null  object
 2   orderUserInfo         26681 non-null  object
 3   lastUpdatedTime       26681 non-null  datetime64[ns]
 4   paymentInfo           26681 non-null  object
 5   fseName               26681 non-null  object
 6   status                26681 non-null  object
 7   kotNos                26681 non-null  object
 8   invoicePaymentType    26681 non-null  object
 9   orderIds              26681 non-null  object
 10  createdTime           26681 non-null  datetime64[ns]
 11  orderTypes            26681 non-null  object
 12  billingModes          26681 non-null  object
 13  id                    26681 non-null  object
 14  invoiceId             26681 non-null  object
 15  orderNumbers          26681 non-null  object
 16  handledBy             26681 non-null  object
 17  invoicePaymentStatus  26681 non-null  object
 18  tableNumbers          26681 non-null  object
 19  orderSources          26681 non-null  object
 20  billingInfo           26681 non-null  object
 21  invoiceRefundStatus   26681 non-null  object
 22  payment_mode          26681 non-null  object
 23  hour                  26681 non-null  int32
 24  time_slot             26681 non-null  object
 25  date                  26681 non-null  datetime64[ns]
 26  day_name              26681 non-null  object
 27  month                 26681 non-null  object
 28  revenue               26681 non-null  float64
dtypes: datetime64[ns](3), float64(1), int32(1), int64(1), object(23)
memory usage: 6.0+ MB

In [77]:
print(df['revenue'].dtype)

float64

In [78]:
df = df.drop(columns=['invoiceId'])

In [79]:
df['invoicePaymentStatus'].value_counts()

invoicePaymentStatus
paid       26441
notPaid      230
credit        10
Name: count, dtype: int64

In [80]:
df['status'].value_counts()

status
closed       26432
open           169
cancelled       80
Name: count, dtype: int64

In [81]:
df.to_excel('restaurant_clean_data.xlsx', index=False)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26681 entries, 11 to 53335
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   billNumber            26681 non-null  int64
 1   orderItems            26681 non-null  object
 2   orderUserInfo         26681 non-null  object
 3   lastUpdatedTime       26681 non-null  datetime64[ns]
 4   paymentInfo           26681 non-null  object
 5   fseName               26681 non-null  object
 6   status                26681 non-null  object
 7   kotNos                26681 non-null  object
 8   invoicePaymentType    26681 non-null  object
 9   orderIds              26681 non-null  object
 10  createdTime           26681 non-null  datetime64[ns]
 11  orderTypes            26681 non-null  object
 12  billingModes          26681 non-null  object
 13  id                    26681 non-null  object
 14  orderNumbers          26681 non-null  object
 15  handledBy             26681 non-null  object
 16  invoicePaymentStatus  26681 non-null  object
 17  tableNumbers          26681 non-null  object
 18  orderSources          26681 non-null  object
 19  billingInfo           26681 non-null  object
 20  invoiceRefundStatus   26681 non-null  object
 21  payment_mode          26681 non-null  object
 22  hour                  26681 non-null  int32
 23  time_slot             26681 non-null  object
 24  date                  26681 non-null  datetime64[ns]
 25  day_name              26681 non-null  object
 26  month                 26681 non-null  object
 27  revenue               26681 non-null  float64
dtypes: datetime64[ns](3), float64(1), int32(1), int64(1), object(22)
memory usage: 5.8+ MB